routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Application;
use App\Session;
use App\VerificationItem;
use Illuminate\Http\Resources\Json\Resource;

Auth::routes();

Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index')->name('welcome');

Route::get('/result', 'FrontController@result')->name('result');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::get('/', 'AdminHomeController@index')->name('admin');
    Route::get('/search/user', 'UserController@search');
    Route::get('/settings', 'AdminHomeController@settings')->name('settings');
    Route::post('/setstat', 'AdminApplicationController@setStat')->name('setStat');
    Route::post('/verification/item/update', 'AdminApplicationController@verify');
    Route::post('/addItem', 'AdminApplicationController@addItem');
    Route::post('/updateRemark', 'AdminApplicationController@updateRemark');
    Route::post('/remark/updateStatus', 'AdminApplicationController@updateRemarkStatus');
    Route::get('/application/{id}/print', 'AdminApplicationController@print');
    Route::get('applicants/attendance', 'ApplicantController@attendance')->name('attendance');
    Route::post('applicant/attendance/mark', 'ApplicantController@mark')->name('markAppearance');
    Route::get('/markentry', 'ApplicantController@markentry')->name('markentry');
    Route::get('/apt', 'ApplicantController@findapt')->name('findapt');
    Route::post('/apt/updateMarks', 'ApplicantController@updateMarks')->name('updateMarks');
    Route::get('/applicants/waitingList', 'ApplicantController@wlist')->name('waitingList');
    Route::post('/applicants/addToEnrolled', 'ApplicantController@addToEnrolled')->name('addToEnrolled');
    Route::get('/applicants/enrolled', 'ApplicantController@enrolled')->name('enrolled');
    Route::post('/applicants/removeFromList', 'ApplicantController@removeFromList')->name('rfl');
    Route::post('/result/updateStatus', 'ResultController@updateStatus')->name('updateResult');
    Route::post('/settings/about/update', 'AdminHomeController@updateAbout')->name('updateAbout');
    Route::get('/settings/instructions', 'AdminHomeController@instructions')->name('instructions');
    Route::post('/settings/instructions/update', 'AdminHomeController@updateInst')->name('updateInst');
    Route::get('/search/application', 'AdminApplicationController@search')->name('searchApplications');


    Route::resource('users', 'UserController');
    Route::resource('session', 'SessionController');
    Route::resource('applications', 'AdminApplicationController');
    Route::resource('types', 'TypeController');
    Route::resource('vitems', 'VerificationItemController');
    Route::resource('documents', 'DocumentController');
    Route::resource('sections', 'SectionController');
    Route::resource('tests', 'TestController');

});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function(){
    Route::get('/', 'ClientHomeController@index')->name('client');
    Route::get('/profile', 'ClientHomeController@profile')->name('profile');
    Route::get('/profile/changepass', 'ClientHomeController@changepass');
    Route::post('/profile/password/change', 'ClientHomeController@changePassword')->name('changePassword');
    Route::get('/about', 'ClientHomeController@about')->name('about');
    Route::post('/section/set', 'ClientHomeController@setSection')->name('setSection');
    Route::post('/section/change', 'ClientHomeController@changeSection')->name('changeSection');
    Route::get('/application/{id}/print', 'ApplicationController@print');
    Route::get('/application/{id}/hallticket', 'ApplicationController@hallticket')->name('getHallTicket');

    Route::resource('application', 'ApplicationController');
});

Route::post('/calcage', 'HomeController@calcage');

Route::get('/test', function(){
    // // Authorisation details.
	// $username = "ktmsulaim@gmail.com";
	// $hash = "21aca9c5fb2b4bbc99a5c80d7f899dd6519657af9be6737775d4958fbfb51a7e";

	// // You shouldn't need to change anything here.
	// $data = "username=ktmsulaim@gmail.com&hash=".$hash;
	// $ch = curl_init('http://api.textlocal.in/balance/?');
	// curl_setopt($ch, CURLOPT_POST, true);
	// curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	// $credits = curl_exec($ch);
	// // This is the number of credits you have left
    // curl_close($ch);

    // $app = Application::find(1);
    // $ids= [];
    // foreach($app->verificationItems as $vitem) {
    //    array_push($ids, $vitem->id);
    // }

    // $items = VerificationItem::all();
    // foreach($items as $item) {
    //     if(in_array($item->id, $ids) === false){
    //         echo $item->id." Is not in the list <br>";
    //     }
    // }

    // print_r($ids);
    // dd($app->verificationItems);

    // App\Section::resetToken(1);
    // App\Applicant::updateRank();
});

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>
        Dashboard
        <small>Darul Hasanath Hifz Al Quran college | Admission portal</small>
    </h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>{{$users}}</h3>

                  <p>User Registrations</p>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="{{route('users.index')}}" class="small-box-footer">
                  More info <i class="fa fa-arrow-circle-right"></i>
                </a>
              </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="small-box bg-green">
                <div class="inner">
                  <h3>{{count($current->applications)}}</h3>

                  <p>Applications</p>
                </div>
                <div class="icon">
                  <i class="fa fa-list-ul"></i>
                </div>
                <a @can('application_access') href="{{route('applications.index')}}" @endcan class="small-box-footer">
                  More info <i class="fa fa-arrow-circle-right"></i>
                </a>
              </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>{{$visitors}}</h3>

                    <p>Unique Visitors</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h5 style="margin-bottom:25px">{{$current ? $current->name : 'No session'}}</h5>

                    <p>Current session</p>
                </div>
                <div class="icon">
                    <i class="fa fa-calendar fa-fw"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/instructions.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>Settings</h1>
@endsection

@section('breadcrumb')
    <li><a href="{{route('settings')}}">Settings</a></li>
    <li class="active"><a href="{{route('instructions')}}">Instructions</a></li>
@endsection

@section('content')
    @if (session('success'))
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Success!</h4>
                    {{session('success')}}
                </div>
            </div>
        </div>
    @endif
    <div class="row">   
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Instructions</h3>
                </div>
                <div class="box-body">
                    <form action="{{Route('updateInst')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <textarea style="resize:none" name="data" id="data" cols="30" rows="10" class="form-control" required>{{old('data', $inst ? $inst->data : '')}}</textarea>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-send fa-fw"></i> Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{asset('js/ckeditor/ckeditor.js')}}"></script>
    <script>
        $(function(){
            CKEDITOR.replace('data')
        });
    </script>
@endsection

resources/views/admin/settings.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>
        Settings
    </h1>
@endsection

@section('breadcrumb')
    <li class="active"><a href="{{route('settings')}}">Settings</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#tab_1" data-toggle="tab">General</a></li>
                  <li><a href="#tab_2" data-toggle="tab">Session</a></li>
                  <li><a href="#tab_3" data-toggle="tab">Application</a></li>
                </ul>
                <div class="tab-content">
                  <div class="tab-pane active" id="tab_1">
                    <b>About institution</b>
                    <div class="form-wrapper">
                        <form action="{{route('updateAbout')}}" method="post">
                            @csrf
                            <table class="table">
                                <tr>
                                    <td width="100">Name</td>
                                    <td><input type="text" class="form-control" name="name" value="{{old('name', $about ? $about->name : '')}}" required></td>
                                    <td width="100">Contact no</td>
                                    <td><input type="number" placeholder="Contact number 1" name="contact" id="contact" min="0" class="form-control" value="{{old('contact', $about ? $about->contact : '')}}" required>
                                        <input type="number" placeholder="Contact number 2" name="contact2" id="contact2" min="0" class="form-control" value="{{old('contact2', $about ? $about->contact2 : '')}}" required></td>
                                </tr>
                                <tr>
                                    <td width="100">Address</td>
                                    <td><textarea name="address" id="address" cols="30" rows="3" style="resize:none" class="form-control" required>{{old('address', $about ? $about->address : '')}}</textarea></td>
                                    <td width="100">Email</td>
                                    <td><input type="email" name="email" id="email" class="form-control" value="{{old('email', $about ? $about->email : '')}}" required></td>
                                </tr>
                                <tr>
                                    <td width="100">Description</td>
                                    <td><textarea name="description" id="desc" cols="30" rows="5" style="resize:none" class="form-control" required>{{old('description', $about ? $about->description : '')}}</textarea></td>
                                    <td width="100">Website</td>
                                    <td><input type="url" name="website" id="website" class="form-control" value="{{old('website', $about ? $about->website : '')}}" required></td>
                                </tr>
                            </table>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                    <p>Give users instructions that's why they can understand the admission procedures. <a href="{{route('instructions')}}">Set up</a></p>
                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="tab_2">
                    <div class="row">
                        <div class="col-md-12 col-xs-12">
                            @if ($session)
                            <div class="text-right">
                                <a class="btn btn-link" href="{{route('session.index')}}">Change</a>
                            </div>
                            <table class="table">
                                <tr>
                                    <th>Current</th>
                                    <td>{{$session->name}} <a href="{{route('session.edit', $session->id)}}"><i title="Edit" class="fa fa-edit fa-fw"></i></a></td>
                                    <td>Name of current session.</td>
                                </tr>
                                <tr>
                                    <th>Year</th>
                                    <td>{{$session->year}}</td>
                                    <td>The year of session, can be used in the application form.</td>
                                </tr>
                                <tr>
                                    <th>From</th>
                                    <td>{{$session->from}}</td>
                                    <td>Date of online registration starts</td>
                                </tr>
                                <tr>
                                    <th>To</th>
                                    <td>{{$session->to}}</td>
                                    <td>Deadline of registration, days left is calculated based on this date.</td>
                                </tr>
                                <tr>
                                    <th>Max. Count</th>
                                    <td>{{$session->max_count}}</td>
                                    <td>Maximum number of students can be enrolled in this session.</td>
                                </tr>
                                <tr>
                                    <th>DOB min</th>
                                    <td>{{$session->birth_min}}</td>
                                    <td>Minimum date of birth date of applicant</td>
                                </tr>
                                <tr>
                                    <th>DOB max</th>
                                    <td>{{$session->birth_max}}</td>
                                    <td>Maximum date of birth date of applicant</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    <td>{!! $session->status == 1 ? '<span class="label label-success">ON</span>' : '<span class="label label-danger">OFF</span>' !!}</td>
                                    <td>Status of admission, whether it is open or closed.</td>
                                </tr>
                            </table>

                            @else
                                <p class="text-muted text-center"><i class="fa fa-frown-o fa-fw"></i> No current session found, set it <a href="{{route('session.index')}}">now</a></p>
                            @endif
                        </div>
                    </div>
                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="tab_3">
                      <div>
                          <a href="{{route('documents.index')}}" class="btn btn-link"><i class="fa fa-files-o fa-fw"></i> Documents</a>
                      </div>
                    <table class="table table-bordered">
                        <tr>
                            <th width="150">Form</th>
                            <td>
                                @if ($form)
                                    <iframe src="{{asset('/ViewerJS/#..'.$form->filename)}}" frameborder="0" width="500" height="300" allowfullscreen webkitallowfullscreen></iframe>
                                    <div class="form-details">
                                        <b>{{$form->title}} <a data-toggle="tooltip" data-original-title="Edit" data-placement="right" href="{{route('documents.edit', $form->id)}}"><i class="fa fa-edit fa-fw"></i></a></b>
                                        <p>{{$form->details}}</p>
                                    </div>
                                @else
                                    <p class="text-muted">
                                        <i class="fa fa-frown-o fa-fw"></i> No form file has been set. Upload it <a href="{{route('documents.create')}}">now</a>!
                                    </p>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <th>Hall ticket</th>
                            <td>
                                @if ($hallTicket)
                                    <iframe src="{{asset('/ViewerJS/#..'.$hallTicket->filename)}}" frameborder="0" width="500" height="300" allowfullscreen webkitallowfullscreen></iframe>
                                    <div class="form-details">
                                        <b>{{$hallTicket->title}} <a data-toggle="tooltip" data-original-title="Edit" data-placement="right" href="{{route('documents.edit', $hallTicket->id)}}"><i class="fa fa-edit fa-fw"></i></a></b>
                                        <p>{{$hallTicket->details}}</p>
                                    </div>
                                @else
                                    <p class="text-muted">
                                        <i class="fa fa-frown-o fa-fw"></i> No hall ticket file has been set. Upload it <a href="{{route('documents.create')}}">now</a>!
                                    </p>
                                @endif
                            </td>
                        </tr>
                    </table>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div>
        </div>
    </div>
@endsection