routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Application;
use App\Session;
use App\VerificationItem;
use Illuminate\Http\Resources\Json\Resource;

Auth::routes();

Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index')->name('welcome');

Route::get('/result', 'FrontController@result')->name('result');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::get('/', 'AdminHomeController@index')->name('admin');
    Route::get('/search/user', 'UserController@search');
    Route::get('/settings', 'AdminHomeController@settings')->name('settings');
    Route::post('/setstat', 'AdminApplicationController@setStat')->name('setStat');
    Route::post('/verification/item/update', 'AdminApplicationController@verify');
    Route::post('/addItem', 'AdminApplicationController@addItem');
    Route::post('/updateRemark', 'AdminApplicationController@updateRemark');
    Route::post('/remark/updateStatus', 'AdminApplicationController@updateRemarkStatus');
    Route::get('/application/{id}/print', 'AdminApplicationController@print');
    Route::get('applicants/attendance', 'ApplicantController@attendance')->name('attendance');
    Route::post('applicant/attendance/mark', 'ApplicantController@mark')->name('markAppearance');
    Route::get('/markentry', 'ApplicantController@markentry')->name('markentry');
    Route::get('/apt', 'ApplicantController@findapt')->name('findapt');
    Route::post('/apt/updateMarks', 'ApplicantController@updateMarks')->name('updateMarks');
    Route::get('/applicants/waitingList', 'ApplicantController@wlist')->name('waitingList');
    Route::post('/applicants/addToEnrolled', 'ApplicantController@addToEnrolled')->name('addToEnrolled');
    Route::get('/applicants/enrolled', 'ApplicantController@enrolled')->name('enrolled');
    Route::post('/applicants/removeFromList', 'ApplicantController@removeFromList')->name('rfl');
    Route::post('/result/updateStatus', 'ResultController@updateStatus')->name('updateResult');
    Route::post('/settings/about/update', 'AdminHomeController@updateAbout')->name('updateAbout');
    Route::get('/settings/instructions', 'AdminHomeController@instructions')->name('instructions');
    Route::post('/settings/instructions/update', 'AdminHomeController@updateInst')->name('updateInst');
    Route::get('/search/application', 'AdminApplicationController@search')->name('searchApplications');


    Route::resource('users', 'UserController');
    Route::resource('session', 'SessionController');
    Route::resource('applications', 'AdminApplicationController');
    Route::resource('types', 'TypeController');
    Route::resource('vitems', 'VerificationItemController');
    Route::resource('documents', 'DocumentController');
    Route::resource('sections', 'SectionController');
    Route::resource('tests', 'TestController');

});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function(){
    Route::get('/', 'ClientHomeController@index')->name('client');
    Route::get('/profile', 'ClientHomeController@profile')->name('profile');
    Route::get('/profile/changepass', 'ClientHomeController@changepass');
    Route::post('/profile/password/change', 'ClientHomeController@changePassword')->name('changePassword');
    Route::get('/about', 'ClientHomeController@about')->name('about');
    Route::post('/section/set', 'ClientHomeController@setSection')->name('setSection');
    Route::post('/section/change', 'ClientHomeController@changeSection')->name('changeSection');
    Route::get('/application/{id}/print', 'ApplicationController@print');
    Route::get('/application/{id}/hallticket', 'ApplicationController@hallticket')->name('getHallTicket');

    Route::resource('application', 'ApplicationController');
});

Route::post('/calcage', 'HomeController@calcage');

Route::get('/test', function(){
    // // Authorisation details.
	// $username = "ktmsulaim@gmail.com";
	// $hash = "21aca9c5fb2b4bbc99a5c80d7f899dd6519657af9be6737775d4958fbfb51a7e";

	// // You shouldn't need to change anything here.
	// $data = "username=ktmsulaim@gmail.com&hash=".$hash;
	// $ch = curl_init('http://api.textlocal.in/balance/?');
	// curl_setopt($ch, CURLOPT_POST, true);
	// curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	// $credits = curl_exec($ch);
	// // This is the number of credits you have left
    // curl_close($ch);

    // $app = Application::find(1);
    // $ids= [];
    // foreach($app->verificationItems as $vitem) {
    //    array_push($ids, $vitem->id);
    // }

    // $items = VerificationItem::all();
    // foreach($items as $item) {
    //     if(in_array($item->id, $ids) === false){
    //         echo $item->id." Is not in the list <br>";
    //     }
    // }

    // print_r($ids);
    // dd($app->verificationItems);

    // App\Section::resetToken(1);
    // App\Applicant::updateRank();
});

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Type;
use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('verification_access')) {
            $types = Type::all();
            return view('admin.validation.types.index', compact('types'));
        } else {
            return back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::allows('verification_access')) {
            $types = Type::all();
            return view('admin.validation.types.index', compact('types'));
        } else {
            return back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Gate::allows('verification_access')) {
            if(!empty($request->name)){
                $type = Type::create($request->all());
                return redirect()->route('types.index');
            }else {
                return redirect()->route('types.create');
            }
        } else {
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::allows('verification_access')) {
            $types = Type::all();
            $t = Type::findOrFail($id);
            return view('admin.validation.types.edit', compact('types', 't'));
        }else{
            return back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Gate::allows('verification_access')){
            $type = Type::findOrFail($id);
            if(!empty($request->name)){
                $type->update($request->all());
                return redirect()->route('types.index');
            }
        }else{
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Gate::allows('verification_access')){
            $type = Type::findOrFail($id);
            $type->delete();
            return redirect()->route('types.index');
        }else{
            return back();
        }
    }
}

resources/views/admin/validation/types/edit.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>Types</h1>
@endsection

@section('breadcrumb')
    <li><a href="{{route('types.index')}}">Types</a></li>
    <li class="active"><a href="{{route('types.edit', $t->id)}}">Edit</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Items in {{$t->name}}</h3>
                </div>
                <div class="box-body">

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Created on</th>
                                    <th width="50"></th>
                                    <th width="50"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (count($t->verificationItems) > 0)
                                    @foreach ($t->verificationItems as $key => $vitem)
                                    <tr>
                                        <td>{{$key + 1}}</td>
                                        <td>{{$vitem->name}}</td>
                                        <td>{{date('F d, Y h:i A', strtotime($vitem->created_at))}}</td>
                                        <td><a class="btn btn-link btn-sm" href="{{route('vitems.edit', $vitem->id)}}"><i class="fa fa-edit fa-fw"></i></a></td>
                                        <td>
                                            <form action="{{route('vitems.destroy', $vitem->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-link btn-sm" type="submit"><i class="fa fa-trash fa-fw"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif
                                <tr>
                                    <td>#</td>
                                    <td colspan="3"><input form="item" type="text" name="name" id="name" placeholder="Name of item" class="form-control" required></td>
                                    <td><button class="btn btn-primary" form="item" type="submit"><i class="fa fa-plus fa-fw"></i> Create</button></td>
                                </tr>
                            </tbody>
                        </table>
                        <form id="item" action="{{route('vitems.store')}}" method="post">
                            @csrf
                            @method('POST')
                            <input type="hidden" name="type_id" value="{{$t->id}}">
                        </form>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit {{$t->name}}</h3>
                </div>
                <div class="box-body">
                    <form action="{{route('types.update', $t->id)}}" method="post">
                        @csrf
                        @method('PATCH')

                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" class="form-control" value="{{old('name', $t->name)}}" required>
                        </div>

                        <div class="text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-send fa-fw"></i> Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
@endsection

resources/views/admin/validation/types/index.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>Types</h1>
@endsection

@section('breadcrumb')
    <li class="active"><a href="{{route('types.index')}}">Types</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">All types</h3>
                </div>
                <div class="box-body">
                    @if (count($types) > 0)
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Items</th>
                                    <th>Created on</th>
                                    <th width="50"></th>
                                    <th width="50"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($types as $key => $type)
                                <tr>
                                    <td>{{$key + 1}}</td>
                                    <td>{{$type->name}}</td>
                                    <td>{{count($type->verificationItems)}}</td>
                                    <td>{{date('F d, Y h:i A', strtotime($type->created_at))}}</td>
                                    <td><a class="btn btn-link btn-sm" href="{{route('types.edit', $type->id)}}"><i class="fa fa-edit fa-fw"></i></a></td>
                                    <td>
                                        <form action="{{route('types.destroy', $type->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-link btn-sm" type="submit"><i class="fa fa-trash fa-fw"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                    <p class="text-center text-muted"><i class="fa fa-frown-o fa-fw"></i> No types found!</p>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Create a type</h3>
                </div>
                <div class="box-body">
                    <form action="{{route('types.store')}}" method="post">
                        @csrf
                        @method('POST')

                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" class="form-control" value="{{old('name')}}" required>
                        </div>

                        <div class="text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-plus fa-fw"></i> Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
@endsection