routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Application;
use App\Session;
use App\VerificationItem;
use Illuminate\Http\Resources\Json\Resource;

Auth::routes();

Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index')->name('welcome');

Route::get('/result', 'FrontController@result')->name('result');

Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::get('/', 'AdminHomeController@index')->name('admin');
    Route::get('/search/user', 'UserController@search');
    Route::get('/settings', 'AdminHomeController@settings')->name('settings');
    Route::post('/setstat', 'AdminApplicationController@setStat')->name('setStat');
    Route::post('/verification/item/update', 'AdminApplicationController@verify');
    Route::post('/addItem', 'AdminApplicationController@addItem');
    Route::post('/updateRemark', 'AdminApplicationController@updateRemark');
    Route::post('/remark/updateStatus', 'AdminApplicationController@updateRemarkStatus');
    Route::get('/application/{id}/print', 'AdminApplicationController@print');
    Route::get('applicants/attendance', 'ApplicantController@attendance')->name('attendance');
    Route::post('applicant/attendance/mark', 'ApplicantController@mark')->name('markAppearance');
    Route::get('/markentry', 'ApplicantController@markentry')->name('markentry');
    Route::get('/apt', 'ApplicantController@findapt')->name('findapt');
    Route::post('/apt/updateMarks', 'ApplicantController@updateMarks')->name('updateMarks');
    Route::get('/applicants/waitingList', 'ApplicantController@wlist')->name('waitingList');
    Route::post('/applicants/addToEnrolled', 'ApplicantController@addToEnrolled')->name('addToEnrolled');
    Route::get('/applicants/enrolled', 'ApplicantController@enrolled')->name('enrolled');
    Route::post('/applicants/removeFromList', 'ApplicantController@removeFromList')->name('rfl');
    Route::post('/result/updateStatus', 'ResultController@updateStatus')->name('updateResult');
    Route::post('/settings/about/update', 'AdminHomeController@updateAbout')->name('updateAbout');
    Route::get('/settings/instructions', 'AdminHomeController@instructions')->name('instructions');
    Route::post('/settings/instructions/update', 'AdminHomeController@updateInst')->name('updateInst');
    Route::get('/search/application', 'AdminApplicationController@search')->name('searchApplications');


    Route::resource('users', 'UserController');
    Route::resource('session', 'SessionController');
    Route::resource('applications', 'AdminApplicationController');
    Route::resource('types', 'TypeController');
    Route::resource('vitems', 'VerificationItemController');
    Route::resource('documents', 'DocumentController');
    Route::resource('sections', 'SectionController');
    Route::resource('tests', 'TestController');

});

Route::group(['prefix' => 'client', 'middleware' => ['client']], function(){
    Route::get('/', 'ClientHomeController@index')->name('client');
    Route::get('/profile', 'ClientHomeController@profile')->name('profile');
    Route::get('/profile/changepass', 'ClientHomeController@changepass');
    Route::post('/profile/password/change', 'ClientHomeController@changePassword')->name('changePassword');
    Route::get('/about', 'ClientHomeController@about')->name('about');
    Route::post('/section/set', 'ClientHomeController@setSection')->name('setSection');
    Route::post('/section/change', 'ClientHomeController@changeSection')->name('changeSection');
    Route::get('/application/{id}/print', 'ApplicationController@print');
    Route::get('/application/{id}/hallticket', 'ApplicationController@hallticket')->name('getHallTicket');

    Route::resource('application', 'ApplicationController');
});

Route::post('/calcage', 'HomeController@calcage');

Route::get('/test', function(){
    // // Authorisation details.
	// $username = "ktmsulaim@gmail.com";
	// $hash = "21aca9c5fb2b4bbc99a5c80d7f899dd6519657af9be6737775d4958fbfb51a7e";

	// // You shouldn't need to change anything here.
	// $data = "username=ktmsulaim@gmail.com&hash=".$hash;
	// $ch = curl_init('http://api.textlocal.in/balance/?');
	// curl_setopt($ch, CURLOPT_POST, true);
	// curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	// $credits = curl_exec($ch);
	// // This is the number of credits you have left
    // curl_close($ch);

    // $app = Application::find(1);
    // $ids= [];
    // foreach($app->verificationItems as $vitem) {
    //    array_push($ids, $vitem->id);
    // }

    // $items = VerificationItem::all();
    // foreach($items as $item) {
    //     if(in_array($item->id, $ids) === false){
    //         echo $item->id." Is not in the list <br>";
    //     }
    // }

    // print_r($ids);
    // dd($app->verificationItems);

    // App\Section::resetToken(1);
    // App\Applicant::updateRank();
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Document extends Model
{
    protected $fillable = ['session_id', 'filename', 'title', 'details', 'type'];

    protected $dir = '/files/';
    
    public function session()
    {
        return $this->belongsTo('App\Session');
    }

    public function getFilenameAttribute($val)
    {
        if(!empty($val)){
            return $this->dir.$val;
        }
    }

    public function currentForm()
    {
        return DB::table('current_form')->where('type', '=', 1)->first();
    }

    public static function hasForm()
    {
        if(count(self::where('type', '=', 1)->get()) > 0) {
            return true;
        } else {
            return false;
        }
    }


    public static function hasTicket()
    {
        if(count(self::where('type', '=', 2)->get()) > 0) {
            return true;
        } else {
            return false;
        }
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use App\Http\Requests\DocumentEditRequest;
use App\Http\Requests\DocumentRequest;
use App\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('settings_access')) {
            $session = Session::current();
            $docs = $session->documents()->paginate(10);
            return view('admin.documents.index', compact('session', 'docs'));
        } else {
            return back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::allows('settings_access')) {
            $session = Session::current();
            return view('admin.documents.create', compact('session'));
        } else {
            return back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DocumentRequest $request)
    {
        if(Gate::allows('settings_access')) {
            $input = $request->all();
            // dd((int)$input['type']);
            if($request->hasFile('filename') && $request->file('filename')->isValid()){
                $file = $request->file('filename');
                $filename = time().'.'.$file->getClientOriginalExtension();
                $file->move('files', $filename);
                $input['filename'] = $filename;
            }
            
            $input['type'] = (int)$request->type;

            Document::create($input);
            return redirect()->route('documents.index')->with('success', 'The document has been created!');
        } else {
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Gate::allows('settings_access')) {
            $session = Session::current();
            $doc = $session->documents->find($id);
            return view('admin.documents.edit', compact('doc', 'session'));
        } else {
            return back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(DocumentEditRequest $request, $id)
    {
        if(Gate::allows('settings_access')) {
            $input = $request->all();
            
            if($request->hasFile('filename') && $request->file('filename')->isValid()){
                $file = $request->file('filename');
                $filename = time().'.'.$file->getClientOriginalExtension();
                $file->move('files', $filename);
                $input['filename'] = $filename;
            }
            
            $input['type'] = (int)$request->type;

            $doc = Document::findOrFail($id);
            $doc->update($input);
            return redirect()->route('documents.index')->with('success', 'The document has been updated!');
        } else {
            return back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Gate::allows('settings_access')) {
            $doc = Document::findOrFail($id);

            if(file_exists(public_path().$doc->filename)){
                unlink(public_path().$doc->filename);
            }

            $doc->delete();
            return redirect()->route('documents.index')->with('success', 'The document has been deleted!');
        } else {
            return back();
        }
    }
}

resources/views/admin/documents/create.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>
        Documents
    </h1>
@endsection

@section('breadcrumb')
    <li><a href="{{route('documents.index')}}">Documents</a></li>
    <li class="active"><a href="{{route('documents.create')}}">Create</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">New document</h3>
                </div>
                <div class="box-body">
                    <form action="{{route('documents.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('POST')

                        <input type="hidden" name="session_id" value="{{$session->id}}">

                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" id="title" class="form-control" value="{{old('title')}}" required>
                        </div>

                        <div class="form-group">
                            <label for="details">Details (Optional)</label>
                            <textarea style="resize:none" name="details" id="details" class="form-control" cols="30" rows="5">{{old('details')}}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="type">Type</label>
                            <select name="type" id="type" class="form-control" required>
                                <option value="">Select a document type</option>
                                <option value="1" {{\App\Document::hasForm() === true ? 'disabled' : ''}}>Application form</option>
                                <option value="2" {{\App\Document::hasTicket() === true ? 'disabled' : ''}}>Hall ticket</option>
                                <option value="0">Other</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="filename">File (.pdf)</label>
                            <input type="file" accept=".pdf" name="filename" id="filename" class="form-control" required>
                        </div>

                        <div class="text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-plus fa-fw"></i> Create</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
            @if (count($errors) > 0)
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">Error</h3>
                    </div>
                    <div class="box-body">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function(){
            $('#filename').fileinput({
                maxFileSize: 1024,
                showUpload: false,
                allowedFileExtensions: ['pdf']
            });
        });
    </script>
@endsection

resources/views/admin/documents/edit.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>
        Documents
    </h1>
@endsection

@section('breadcrumb')
    <li><a href="{{route('documents.index')}}">Documents</a></li>
    <li class="active"><a href="{{route('documents.edit', $doc->id)}}">Edit</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit document</h3>
                </div>
                <div class="box-body">
                    <form action="{{route('documents.update', $doc->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')

                        <input type="hidden" name="session_id" value="{{$session->id}}">

                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" id="title" class="form-control" value="{{old('title', $doc->title)}}" required>
                        </div>

                        <div class="form-group">
                            <label for="details">Details (Optional)</label>
                            <textarea style="resize:none" name="details" id="details" class="form-control" cols="30" rows="5">{{old('details', $doc->details)}}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="type">Type</label>
                            <select name="type" id="type" class="form-control" required>
                                <option value="">Select a document type</option>
                                <option value="1" {{$doc->type === 1 ? 'selected' : ''}} {{\App\Document::hasForm() === true && $doc->type !== 1 ? 'disabled' : ''}}>Application form</option>
                                <option value="2" {{$doc->type === 2 ? 'selected' : ''}}{{\App\Document::hasTicket() === true && $doc->type !== 2 ? 'disabled' : ''}}>Hall ticket</option>
                                <option value="0" {{$doc->type === 0 ? 'selected' : ''}}>Other</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="filename">File (.pdf)</label>
                            <input type="file" accept=".pdf" name="filename" id="filename" class="form-control">
                        </div>

                        <div class="text-right">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-plus fa-fw"></i> Update</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
            @if (count($errors) > 0)
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">Error</h3>
                    </div>
                    <div class="box-body">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif

            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Delete</h3>
                </div>
                <div class="box-body">
                    <p>You are going to delete this document. This can't recover any lost data once it is deleted. continue?</p>
                    <form action="{{route('documents.destroy', $doc->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <div class="text-right">
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash-o fa-fw"></i> Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function(){
            $('#filename').fileinput({
                maxFileSize: 1024,
                showUpload: false,
                allowedFileExtensions: ['pdf'],
                initialPreviewAsData: true,
                initialPreviewFileType: 'pdf', 
                initialPreview: '{{asset($doc->filename)}}'
            });
        });
    </script>
@endsection

resources/views/admin/documents/index.blade.php
@extends('layouts.admin')

@section('page_title')
    <h1>
        Documents
    </h1>
@endsection

@section('breadcrumb')
    <li class="active"><a href="{{route('documents.index')}}">Documents</a></li>
@endsection

@section('content')
    @if ($message = Session::get('success'))
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                {{$message}}
            </div>
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">All documents <small>{{$session->name}}</small></h3>

                    <div class="box-tools">
                        <a href="{{route('documents.create')}}" class="btn btn-primary btn-sm"><i class="fa fa-plus fa-fw"></i> New</a>
                    </div>
                </div>
                <div class="box-body no-padding">
                    @if (count($docs) > 0)
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Preview</th>
                                    <th>Title</th>
                                    <th>Type</th>
                                    <th>Details</th>
                                    <th width="50"></th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                    @foreach ($docs as $key => $doc)
                                        <tr>
                                            <td>{{$key + 1}}</td>
                                            <td><iframe src="{{asset('/ViewerJS/#..'.$doc->filename)}}" width="" height="200" frameborder="0" allowfullscreen webkitallowfullscreen></iframe></td>
                                            <td>{{$doc->title}}</td>
                                            <td>
                                                @if ($doc->type === 1)
                                                    {{'Application form'}}
                                                @elseif($doc->type === 2)
                                                    {{'Hall ticket'}}
                                                @else
                                                    {{'Other'}}
                                                @endif
                                            </td>
                                            <td>{{$doc->details}}</td>
                                            <td><a href="{{route('documents.edit', $doc->id)}}"><i class="fa fa-edit fa-fw"></i></a></td>
                                        </tr>
                                    @endforeach
                            
                            </tbody>
                        </table>
                    @else
                        <p class="text-center text-muted box-body"><i class="fa fa-frown-o fa-fw"></i> No document found!</p>
                    @endif
                </div>
                @if (count($docs) > 0)
                    <div class="box-footer">
                        {{$docs->links()}}
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection